### ISSUE TITLE
Karma 3.0.0 -> errors

### ISSUE THREAD

**Issue by kmdrGroch** [stryker-mutator/stryker#1079]
### Tags 😛
- For future; "warning" error; Information for developers

### Summary

There are is an issue with ``Karma 3.0.0``; Since they updated one dependency ``log4js [version 3.0]`` it can throw some errors (then don't influence on results though i think); error -> ``log4js A worker log process hung up unexpectedly { Error: read ECONNRESET at TCP.onread (net.js:659:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }``

### Tools

- Karma 3.0.0
- Stryker 0.26.1
- Jasmine 3.2.0

### Log
[Log](https://github.com/stryker-mutator/stryker/files/2280219/stryker.log)

**Comment by kmdrGroch** [comment]
@nicojs i also have told karma crew about it, thought they said it is not their fault, and i should tell it to "authors of package". It doesn't have impact on stryker functionality though - it just throws errors ._.

**Comment by simondel** [comment]
@kmdrGroch is this fixed now?

**Comment by kmdrGroch** [comment]
I havent seen this bug for some time. I would need to reproduce it to check it, but since we still don't support cross-folder testing, it should be closed for now.

**Comment by Wmaarts** [comment]
I have the same issue. Using Karma 3.0.0 gives me the following warning repeatedly:
`11:03:43 (20088) ERROR log4js A worker log process hung up unexpectedly { Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }`

It doesn't impact functionality it seems: the tests run fine. (so not a breaking issue). And downgrading Karma to 2.0.5 removed the warnings. 

Versions: 
`
    "jasmine-core": "~2.99.1",
    "karma": "~3.0.0",
    "stryker": "^0.32.0",
    "stryker-api": "^0.21.5",
    "stryker-karma-runner": "^0.20.2",
`

**Comment by nicojs** [comment]
This is fixed with #1246. It is caused by a raise condition in log4js (ironically, it was I that introduced the log message with a PR here: https://github.com/log4js-node/log4js-node/pull/714)
