### ISSUE TITLE
Problems running stryker with babel 7

### ISSUE THREAD

**Issue by Powerade** [stryker-mutator/stryker#1316]
Hello everyone,
I'm having trouble running stryker with babel 7 where it tries to use babel 6? Even though I'm using babel 7

I have the current lib configurations:

```js
stryker.conf.js:

module.exports = function(config) {
    config.set({
        mutate: ['js/**/*.js?(x)', '!js/**/*@(-test).js?(x)'],
        mutator: 'javascript',
        testRunner: 'jest',
        reporters: ['progress', 'clear-text', 'html'],
        coverageAnalysis: 'off',
        jest: {
            projectType: 'react',
            config: require('./stryker.jest.conf')
        },
        transpilers: ['babel'],
        babelrcFile: '.babelrc',
        logLevel: 'info'
    });
};
```

```js
.babelrc

{
    "presets": [
        "@babel/env",
        "@babel/preset-react"
    ],
    "plugins": [
        "react-hot-loader/babel",
        "@babel/plugin-proposal-class-properties",
        "@babel/plugin-syntax-dynamic-import",
        "@babel/plugin-proposal-optional-catch-binding",
        "@babel/plugin-proposal-optional-chaining",
        "@babel/plugin-proposal-nullish-coalescing-operator"
    ]
}
```

### Summary
```
Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". 
If you are sure you have a compatible version of @babel/core, it is 
likely that something in your build process is loading the wrong version. 
Inspect the stack trace of this error to look for the first entry 
that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
```

### Stryker environment

```
"stryker": "^0.34.0",
"stryker-api": "^0.23.0",
"stryker-babel-transpiler": "^0.8.0",
"stryker-cli": "^0.2.0",
"stryker-html-reporter": "^0.17.0",
"stryker-javascript-mutator": "^0.13.0",
"stryker-jest-runner": "^1.3.0",
"babel-core": "^7.0.0-bridge.0",
"@babel/core": "7.1.6",
"@babel/plugin-proposal-class-properties": "7.1.0",
"@babel/plugin-proposal-export-namespace-from": "7.0.0",
"@babel/plugin-proposal-json-strings": "7.0.0",
"@babel/plugin-proposal-nullish-coalescing-operator": "7.0.0",
"@babel/plugin-proposal-optional-catch-binding": "7.0.0",
"@babel/plugin-proposal-optional-chaining": "7.0.0",
"@babel/plugin-proposal-throw-expressions": "7.0.0",
"@babel/plugin-syntax-dynamic-import": "7.0.0",
"@babel/preset-env": "7.1.6",
"@babel/preset-react": "7.0.0",
"@babel/register": "7.0.0",
"@babel/runtime": "7.1.5",
"babel-jest": "23.6.0",
```

```
+-- jest@^1.3.0
```

### Your Environment

| software         | version(s)
| ---------------- | -------  
| node             |  11.1.0
| npm              | 6.5.0
| Operating System |  osx

**Comment by vpanichkin** [comment]
Working with this configuration: 
    "babel-core": "^7.0.0-bridge.0",
    "@babel/cli": "^7.0.0",
    "@babel/preset-flow": "^7.0.0",
    "@babel/preset-env": "^7.3.1",
    "babel-jest": "^24.0.0",
    "@babel/core":"^7.2.2",

**Comment by nicojs** [comment]
Thanks for reporting. I just released babel 7 support in the `stryker-babel-transpiler`.  Please let us know if there is any issue.

`npm i -D stryker@0.25 stryker-api@0.24 stryker-babel-transpiler@0.10`

**Comment by Powerade** [comment]
Still not working.


"stryker": "^0.25.1",

"stryker-api": "^0.24.0",

"stryker-babel-transpiler": "^0.10.0",

"stryker-cli": "0.2.0",

"stryker-html-reporter": "^0.17.0",

"stryker-javascript-mutator": "^0.13.0",

"stryker-jest-runner": "^1.3.0",

"@babel/preset-env": "^7.3.1",

"@babel/core": "^7.2.2",


`11:25:38 (27036) WARN PluginLoader Error during loading "stryker-babel-transpiler" plugin:
  Cannot find module 'typed-inject/src/api/InjectionToken'
11:25:38 (27036) FATAL ConfigValidator Value "undefined" is invalid for `timeoutMs`. Expected a number
11:25:38 (27036) FATAL ConfigValidator Value "undefined" is invalid for `port`. Expected a number
Stryker could not recover from this configuration error, see fatal log message(s) above.
(node:27036) Warning: DEPRECATED. The "progress-append-only" reporter plugin is registered with the deprecated "Factory" api. You might need to update your plugins. If you are the plugin creator, please see https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/api/plugins.md
(node:27036) Warning: DEPRECATED. The "progress" reporter plugin is registered with the deprecated "Factory" api. You might need to update your plugins. If you are the plugin creator, please see https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/api/plugins.md
(node:27036) Warning: DEPRECATED. The "dots" reporter plugin is registered with the deprecated "Factory" api. You might need to update your plugins. If you are the plugin creator, please see https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/api/plugins.md
(node:27036) Warning: DEPRECATED. The "clear-text" reporter plugin is registered with the deprecated "Factory" api. You might need to update your plugins. If you are the plugin creator, please see https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/api/plugins.md
(node:27036) Warning: DEPRECATED. The "event-recorder" reporter plugin is registered with the deprecated "Factory" api. You might need to update your plugins. If you are the plugin creator, please see https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/api/plugins.md
(node:27036) Warning: DEPRECATED. The "dashboard" reporter plugin is registered with the deprecated "Factory" api. You might need to update your plugins. If you are the plugin creator, please see https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/api/plugins.md
(node:27036) Warning: DEPRECATED. The "es5" mutant-generator plugin is registered with the deprecated "Factory" api. You might need to update your plugins. If you are the plugin creator, please see https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/api/plugins.md
(node:27036) Warning: DEPRECATED call to `getLogger('StrykerCli')` is deprecated. Stryker plugins should use dependency injection to let loggers be injected
(node:27036) Warning: DEPRECATED call to `getLogger('Stryker')` is deprecated. Stryker plugins should use dependency injection to let loggers be injected
(node:27036) Warning: DEPRECATED call to `getLogger('ConfigReader')` is deprecated. Stryker plugins should use dependency injection to let loggers be injected
(node:27036) Warning: DEPRECATED call to `getLogger('PluginLoader')` is deprecated. Stryker plugins should use dependency injection to let loggers be injected
(node:27036) Warning: DEPRECATED. The "html" reporter plugin is registered with the deprecated "Factory" api. You might need to update your plugins. If you are the plugin creator, please see https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/api/plugins.md
(node:27036) Warning: DEPRECATED. The "ArrayLiteralMutator" nodeMutator plugin is registered with the deprecated "Factory" api. You might need to update your plugins. If you are the plugin creator, please see https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/api/plugins.md
(node:27036) Warning: DEPRECATED. The "ArrayNewExpressionMutator" nodeMutator plugin is registered with the deprecated "Factory" api. You might need to update your plugins. If you are the plugin creator, please see https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/api/plugins.md
(node:27036) Warning: DEPRECATED. The "BinaryExpressionMutator" nodeMutator plugin is registered with the deprecated "Factory" api. You might need to update your plugins. If you are the plugin creator, please see https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/api/plugins.md
(node:27036) Warning: DEPRECATED. The "BlockMutator" nodeMutator plugin is registered with the deprecated "Factory" api. You might need to update your plugins. If you are the plugin creator, please see https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/api/plugins.md
(node:27036) Warning: DEPRECATED. The "BooleanSubstitutionMutator" nodeMutator plugin is registered with the deprecated "Factory" api. You might need to update your plugins. If you are the plugin creator, please see https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/api/plugins.md
(node:27036) Warning: DEPRECATED. The "ConditionalExpressionMutator" nodeMutator plugin is registered with the deprecated "Factory" api. You might need to update your plugins. If you are the plugin creator, please see https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/api/plugins.md
(node:27036) Warning: DEPRECATED. The "DoStatementMutator" nodeMutator plugin is registered with the deprecated "Factory" api. You might need to update your plugins. If you are the plugin creator, please see https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/api/plugins.md
(node:27036) Warning: DEPRECATED. The "ForStatementMutator" nodeMutator plugin is registered with the deprecated "Factory" api. You might need to update your plugins. If you are the plugin creator, please see https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/api/plugins.md
(node:27036) Warning: DEPRECATED. The "IfStatementMutator" nodeMutator plugin is registered with the deprecated "Factory" api. You might need to update your plugins. If you are the plugin creator, please see https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/api/plugins.md
(node:27036) Warning: DEPRECATED. The "ObjectLiteralMutator" nodeMutator plugin is registered with the deprecated "Factory" api. You might need to update your plugins. If you are the plugin creator, please see https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/api/plugins.md
(node:27036) Warning: DEPRECATED. The "PostfixUnaryExpressionMutator" nodeMutator plugin is registered with the deprecated "Factory" api. You might need to update your plugins. If you are the plugin creator, please see https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/api/plugins.md
(node:27036) Warning: DEPRECATED. The "PrefixUnaryExpressionMutator" nodeMutator plugin is registered with the deprecated "Factory" api. You might need to update your plugins. If you are the plugin creator, please see https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/api/plugins.md
(node:27036) Warning: DEPRECATED. The "StringLiteralMutator" nodeMutator plugin is registered with the deprecated "Factory" api. You might need to update your plugins. If you are the plugin creator, please see https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/api/plugins.md
(node:27036) Warning: DEPRECATED. The "SwitchCaseMutator" nodeMutator plugin is registered with the deprecated "Factory" api. You might need to update your plugins. If you are the plugin creator, please see https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/api/plugins.md
(node:27036) Warning: DEPRECATED. The "WhileStatementMutator" nodeMutator plugin is registered with the deprecated "Factory" api. You might need to update your plugins. If you are the plugin creator, please see https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/api/plugins.md
(node:27036) Warning: DEPRECATED. The "javascript" mutant-generator plugin is registered with the deprecated "Factory" api. You might need to update your plugins. If you are the plugin creator, please see https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/api/plugins.md
(node:27036) Warning: DEPRECATED call to `getLogger('JestTestAdapterFactory')` is deprecated. Stryker plugins should use dependency injection to let loggers be injected
(node:27036) Warning: DEPRECATED. The "jest" config-reader plugin is registered with the deprecated "Factory" api. You might need to update your plugins. If you are the plugin creator, please see https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/api/plugins.md
(node:27036) Warning: DEPRECATED. The "jest" testrunner plugin is registered with the deprecated "Factory" api. You might need to update your plugins. If you are the plugin creator, please see https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/api/plugins.md
(node:27036) Warning: DEPRECATED call to `getLogger('JestConfigEditor')` is deprecated. Stryker plugins should use dependency injection to let loggers be injected
(node:27036) Warning: DEPRECATED call to `getLogger('ReporterOrchestrator')` is deprecated. Stryker plugins should use dependency injection to let loggers be injected
(node:27036) Warning: DEPRECATED call to `getLogger('BroadcastReporter')` is deprecated. Stryker plugins should use dependency injection to let loggers be injected
(node:27036) Warning: DEPRECATED call to `getLogger('TestFrameworkOrchestrator')` is deprecated. Stryker plugins should use dependency injection to let loggers be injected
(node:27036) Warning: DEPRECATED call to `getLogger('ConfigValidator')` is deprecated. Stryker plugins should use dependency injection to let loggers be injected`

Am I missing something? Thank you

**Comment by brunachamon-hotmart** [comment]
Any updates? I'm facing same issue =(
